---
driver:
  name: vagrant

provisioner:
  name: chef_zero

  product_name: chef
  product_version: 14

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[elkserver::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
